[package]
name = "rest_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.146"
uuid = { version = "1.19.0", features = ["serde","v4"]}
